package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminid;
     private String adminntlogin;
     private Date adminlastlogin;
     private Integer adminright;
     private String adminemail;
     private String adminphone;
     private String admindescription;
     private Set surveytemplates = new HashSet(0);

    public Admin() {
    }

    public Admin(String adminntlogin, Date adminlastlogin, Integer adminright, String adminemail, String adminphone, String admindescription, Set surveytemplates) {
       this.adminntlogin = adminntlogin;
       this.adminlastlogin = adminlastlogin;
       this.adminright = adminright;
       this.adminemail = adminemail;
       this.adminphone = adminphone;
       this.admindescription = admindescription;
       this.surveytemplates = surveytemplates;
    }
   
    public Integer getAdminid() {
        return this.adminid;
    }
    
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }
    public String getAdminntlogin() {
        return this.adminntlogin;
    }
    
    public void setAdminntlogin(String adminntlogin) {
        this.adminntlogin = adminntlogin;
    }
    public Date getAdminlastlogin() {
        return this.adminlastlogin;
    }
    
    public void setAdminlastlogin(Date adminlastlogin) {
        this.adminlastlogin = adminlastlogin;
    }
    public Integer getAdminright() {
        return this.adminright;
    }
    
    public void setAdminright(Integer adminright) {
        this.adminright = adminright;
    }
    public String getAdminemail() {
        return this.adminemail;
    }
    
    public void setAdminemail(String adminemail) {
        this.adminemail = adminemail;
    }
    public String getAdminphone() {
        return this.adminphone;
    }
    
    public void setAdminphone(String adminphone) {
        this.adminphone = adminphone;
    }
    public String getAdmindescription() {
        return this.admindescription;
    }
    
    public void setAdmindescription(String admindescription) {
        this.admindescription = admindescription;
    }
    public Set getSurveytemplates() {
        return this.surveytemplates;
    }
    
    public void setSurveytemplates(Set surveytemplates) {
        this.surveytemplates = surveytemplates;
    }




}


