package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0



/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private Integer answerid;
     private Membersurvey membersurvey;
     private Question question;
     private Integer answerscore;

    public Answer() {
    }

	
    public Answer(Membersurvey membersurvey, Question question) {
        this.membersurvey = membersurvey;
        this.question = question;
    }
    public Answer(Membersurvey membersurvey, Question question, Integer answerscore) {
       this.membersurvey = membersurvey;
       this.question = question;
       this.answerscore = answerscore;
    }
   
    public Integer getAnswerid() {
        return this.answerid;
    }
    
    public void setAnswerid(Integer answerid) {
        this.answerid = answerid;
    }
    public Membersurvey getMembersurvey() {
        return this.membersurvey;
    }
    
    public void setMembersurvey(Membersurvey membersurvey) {
        this.membersurvey = membersurvey;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public Integer getAnswerscore() {
        return this.answerscore;
    }
    
    public void setAnswerscore(Integer answerscore) {
        this.answerscore = answerscore;
    }




}


