package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer memberid;
     private Team team;
     private String memberntlogin;
     private Integer memberrole;
     private String membername;
     private String managernt;
     private String managername;
     private Set membersurveysForMemberMemberidTarget = new HashSet(0);
     private Set membersurveysForMemberMemberid = new HashSet(0);

    public Member() {
    }

	
    public Member(Team team) {
        this.team = team;
    }
    public Member(Team team, String memberntlogin, Integer memberrole, String membername, String managernt, String managername, Set membersurveysForMemberMemberidTarget, Set membersurveysForMemberMemberid) {
       this.team = team;
       this.memberntlogin = memberntlogin;
       this.memberrole = memberrole;
       this.membername = membername;
       this.managernt = managernt;
       this.managername = managername;
       this.membersurveysForMemberMemberidTarget = membersurveysForMemberMemberidTarget;
       this.membersurveysForMemberMemberid = membersurveysForMemberMemberid;
    }
   
    public Integer getMemberid() {
        return this.memberid;
    }
    
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }
    public String getMemberntlogin() {
        return this.memberntlogin;
    }
    
    public void setMemberntlogin(String memberntlogin) {
        this.memberntlogin = memberntlogin;
    }
    public Integer getMemberrole() {
        return this.memberrole;
    }
    
    public void setMemberrole(Integer memberrole) {
        this.memberrole = memberrole;
    }
    public String getMembername() {
        return this.membername;
    }
    
    public void setMembername(String membername) {
        this.membername = membername;
    }
    public String getManagernt() {
        return this.managernt;
    }
    
    public void setManagernt(String managernt) {
        this.managernt = managernt;
    }
    public String getManagername() {
        return this.managername;
    }
    
    public void setManagername(String managername) {
        this.managername = managername;
    }
    public Set getMembersurveysForMemberMemberidTarget() {
        return this.membersurveysForMemberMemberidTarget;
    }
    
    public void setMembersurveysForMemberMemberidTarget(Set membersurveysForMemberMemberidTarget) {
        this.membersurveysForMemberMemberidTarget = membersurveysForMemberMemberidTarget;
    }
    public Set getMembersurveysForMemberMemberid() {
        return this.membersurveysForMemberMemberid;
    }
    
    public void setMembersurveysForMemberMemberid(Set membersurveysForMemberMemberid) {
        this.membersurveysForMemberMemberid = membersurveysForMemberMemberid;
    }




}


