package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Membersurvey generated by hbm2java
 */
public class Membersurvey  implements java.io.Serializable {


     private Integer membersurveyid;
     private Member memberByMemberMemberid;
     private Member memberByMemberMemberidTarget;
     private Survey survey;
     private Integer membersurveystatus;
     private Date membersurveyfinishtime;
     private String membersurveycol;
     private Set answers = new HashSet(0);

    public Membersurvey() {
    }

	
    public Membersurvey(Member memberByMemberMemberid, Member memberByMemberMemberidTarget, Survey survey) {
        this.memberByMemberMemberid = memberByMemberMemberid;
        this.memberByMemberMemberidTarget = memberByMemberMemberidTarget;
        this.survey = survey;
    }
    public Membersurvey(Member memberByMemberMemberid, Member memberByMemberMemberidTarget, Survey survey, Integer membersurveystatus, Date membersurveyfinishtime, String membersurveycol, Set answers) {
       this.memberByMemberMemberid = memberByMemberMemberid;
       this.memberByMemberMemberidTarget = memberByMemberMemberidTarget;
       this.survey = survey;
       this.membersurveystatus = membersurveystatus;
       this.membersurveyfinishtime = membersurveyfinishtime;
       this.membersurveycol = membersurveycol;
       this.answers = answers;
    }
   
    public Integer getMembersurveyid() {
        return this.membersurveyid;
    }
    
    public void setMembersurveyid(Integer membersurveyid) {
        this.membersurveyid = membersurveyid;
    }
    public Member getMemberByMemberMemberid() {
        return this.memberByMemberMemberid;
    }
    
    public void setMemberByMemberMemberid(Member memberByMemberMemberid) {
        this.memberByMemberMemberid = memberByMemberMemberid;
    }
    public Member getMemberByMemberMemberidTarget() {
        return this.memberByMemberMemberidTarget;
    }
    
    public void setMemberByMemberMemberidTarget(Member memberByMemberMemberidTarget) {
        this.memberByMemberMemberidTarget = memberByMemberMemberidTarget;
    }
    public Survey getSurvey() {
        return this.survey;
    }
    
    public void setSurvey(Survey survey) {
        this.survey = survey;
    }
    public Integer getMembersurveystatus() {
        return this.membersurveystatus;
    }
    
    public void setMembersurveystatus(Integer membersurveystatus) {
        this.membersurveystatus = membersurveystatus;
    }
    public Date getMembersurveyfinishtime() {
        return this.membersurveyfinishtime;
    }
    
    public void setMembersurveyfinishtime(Date membersurveyfinishtime) {
        this.membersurveyfinishtime = membersurveyfinishtime;
    }
    public String getMembersurveycol() {
        return this.membersurveycol;
    }
    
    public void setMembersurveycol(String membersurveycol) {
        this.membersurveycol = membersurveycol;
    }
    public Set getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set answers) {
        this.answers = answers;
    }




}


