package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer questionid;
     private Surveytemplate surveytemplate;
     private String questioncontent;
     private Integer questioncount;
     private Set answers = new HashSet(0);

    public Question() {
    }

	
    public Question(Surveytemplate surveytemplate) {
        this.surveytemplate = surveytemplate;
    }
    public Question(Surveytemplate surveytemplate, String questioncontent, Integer questioncount, Set answers) {
       this.surveytemplate = surveytemplate;
       this.questioncontent = questioncontent;
       this.questioncount = questioncount;
       this.answers = answers;
    }
   
    public Integer getQuestionid() {
        return this.questionid;
    }
    
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }
    public Surveytemplate getSurveytemplate() {
        return this.surveytemplate;
    }
    
    public void setSurveytemplate(Surveytemplate surveytemplate) {
        this.surveytemplate = surveytemplate;
    }
    public String getQuestioncontent() {
        return this.questioncontent;
    }
    
    public void setQuestioncontent(String questioncontent) {
        this.questioncontent = questioncontent;
    }
    public Integer getQuestioncount() {
        return this.questioncount;
    }
    
    public void setQuestioncount(Integer questioncount) {
        this.questioncount = questioncount;
    }
    public Set getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set answers) {
        this.answers = answers;
    }




}


