package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Survey generated by hbm2java
 */
public class Survey  implements java.io.Serializable {


     private int surveyid;
     private Team team;
     private Surveytemplate surveytemplate;
     private Date surveystarttime;
     private Date surveyfinishtime;
     private Set membersurveys = new HashSet(0);

    public Survey() {
    }

	
    public Survey(int surveyid, Team team, Surveytemplate surveytemplate) {
        this.surveyid = surveyid;
        this.team = team;
        this.surveytemplate = surveytemplate;
    }
    public Survey(int surveyid, Team team, Surveytemplate surveytemplate, Date surveystarttime, Date surveyfinishtime, Set membersurveys) {
       this.surveyid = surveyid;
       this.team = team;
       this.surveytemplate = surveytemplate;
       this.surveystarttime = surveystarttime;
       this.surveyfinishtime = surveyfinishtime;
       this.membersurveys = membersurveys;
    }
   
    public int getSurveyid() {
        return this.surveyid;
    }
    
    public void setSurveyid(int surveyid) {
        this.surveyid = surveyid;
    }
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }
    public Surveytemplate getSurveytemplate() {
        return this.surveytemplate;
    }
    
    public void setSurveytemplate(Surveytemplate surveytemplate) {
        this.surveytemplate = surveytemplate;
    }
    public Date getSurveystarttime() {
        return this.surveystarttime;
    }
    
    public void setSurveystarttime(Date surveystarttime) {
        this.surveystarttime = surveystarttime;
    }
    public Date getSurveyfinishtime() {
        return this.surveyfinishtime;
    }
    
    public void setSurveyfinishtime(Date surveyfinishtime) {
        this.surveyfinishtime = surveyfinishtime;
    }
    public Set getMembersurveys() {
        return this.membersurveys;
    }
    
    public void setMembersurveys(Set membersurveys) {
        this.membersurveys = membersurveys;
    }




}


