package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Surveytemplate generated by hbm2java
 */
public class Surveytemplate  implements java.io.Serializable {


     private Integer surveytemplateid;
     private Admin admin;
     private String surveytemplatetitle;
     private String surveytemplatedescription;
     private Set surveys = new HashSet(0);
     private Set questions = new HashSet(0);

    public Surveytemplate() {
    }

	
    public Surveytemplate(Admin admin) {
        this.admin = admin;
    }
    public Surveytemplate(Admin admin, String surveytemplatetitle, String surveytemplatedescription, Set surveys, Set questions) {
       this.admin = admin;
       this.surveytemplatetitle = surveytemplatetitle;
       this.surveytemplatedescription = surveytemplatedescription;
       this.surveys = surveys;
       this.questions = questions;
    }
   
    public Integer getSurveytemplateid() {
        return this.surveytemplateid;
    }
    
    public void setSurveytemplateid(Integer surveytemplateid) {
        this.surveytemplateid = surveytemplateid;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public String getSurveytemplatetitle() {
        return this.surveytemplatetitle;
    }
    
    public void setSurveytemplatetitle(String surveytemplatetitle) {
        this.surveytemplatetitle = surveytemplatetitle;
    }
    public String getSurveytemplatedescription() {
        return this.surveytemplatedescription;
    }
    
    public void setSurveytemplatedescription(String surveytemplatedescription) {
        this.surveytemplatedescription = surveytemplatedescription;
    }
    public Set getSurveys() {
        return this.surveys;
    }
    
    public void setSurveys(Set surveys) {
        this.surveys = surveys;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


