package com.feedbacksurvey.po;
// Generated Dec 3, 2013 10:32:44 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team  implements java.io.Serializable {


     private Integer teamid;
     private String teamname;
     private String teamdescription;
     private Date teamcreatetime;
     private Set members = new HashSet(0);
     private Set surveys = new HashSet(0);

    public Team() {
    }

    public Team(String teamname, String teamdescription, Date teamcreatetime, Set members, Set surveys) {
       this.teamname = teamname;
       this.teamdescription = teamdescription;
       this.teamcreatetime = teamcreatetime;
       this.members = members;
       this.surveys = surveys;
    }
   
    public Integer getTeamid() {
        return this.teamid;
    }
    
    public void setTeamid(Integer teamid) {
        this.teamid = teamid;
    }
    public String getTeamname() {
        return this.teamname;
    }
    
    public void setTeamname(String teamname) {
        this.teamname = teamname;
    }
    public String getTeamdescription() {
        return this.teamdescription;
    }
    
    public void setTeamdescription(String teamdescription) {
        this.teamdescription = teamdescription;
    }
    public Date getTeamcreatetime() {
        return this.teamcreatetime;
    }
    
    public void setTeamcreatetime(Date teamcreatetime) {
        this.teamcreatetime = teamcreatetime;
    }
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }
    public Set getSurveys() {
        return this.surveys;
    }
    
    public void setSurveys(Set surveys) {
        this.surveys = surveys;
    }




}


